# Generated by Django 4.1.7 on 2023-03-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SplitWiseApp', '0003_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
                ('expense_created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='SplitWiseApp.user')),
                ('participants', models.ManyToManyField(related_name='expense_participants', to='SplitWiseApp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='group',
            name='admins',
            field=models.ManyToManyField(related_name='group_admins', to='SplitWiseApp.user'),
        ),
        migrations.AddField(
            model_name='group',
            name='description',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='group',
            name='participants',
            field=models.ManyToManyField(related_name='group_participants', to='SplitWiseApp.user'),
        ),
        migrations.CreateModel(
            name='ExpensePayingUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExpenseOwingUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField()),
                ('expense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.expense')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SplitWiseApp.user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
